server:
  port: 8082
spring:
  r2dbc:
    username: "postgres"
    password: "postgres"
    url: "r2dbc:postgresql://localhost:5432/ClientPerson"
    initialization-mode: always
    properties:
      sslMode: "DISABLE"
      pool:
        enabled: true
        initial-size: 22
        max-size: 30
        max-idle-time: "5m"
  application:
    name: "ClientPerson"
  devtools:
    add-properties: false
profiles:
  include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/ClientPerson"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: "create"
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: "DEBUG"
    io.r2dbc.postgresql.PARAM: "DEBUG"
    org.springframework.r2dbc: "DEBUG"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
